# serverless.yml

service: express-gifs

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1
  profile: serverless-agent

package:
  exclude:
    - coverage/**
    - node_modules/**
    - src/**
    - test/**
  include:
    - node_modules/express/**
    - src/lambda.js
    - src/app.js

functions:
  lambda:
    handler: src/lambda.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

plugins:
  - serverless-offline
