# serverless.yml

service: express-gifs

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1
  profile: serverless-agent

functions:
  lambda:
    handler: src/lambda.handler
    events:
      - http: GET /
      - http: 'GET {proxy+}'

plugins:
  - serverless-offline
