# serverless.yml

service: express-gifs

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1
  profile: serverless-agent

package:
  individually: true
  exclude:
    - '**/*'

functions:
  lambda:
    handler: src/lambda.handler
    package:
      include:
        - node_modules/**
        - src/app.js
        - src/lambda.js
        - src/routeHandlers.js
        - src/utils.js
    events:
      - http: GET /
      - http: 'GET {proxy+}'
